efcoreApp/Controllers/KursController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers {
    public class KursController : Controller {

        private readonly DataContext _context;

        public KursController(DataContext dataContext) {
            _context = dataContext;
        }

        public async Task<IActionResult> Create() {
            ViewBag.Ogretmenler = new SelectList(await _context.Ogretmenler.ToListAsync(), "OgretmenId", "AdSoyad");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Kurs model) {
            _context.Kurslar.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Index() {

            var kurslar = await _context.Kurslar.Include(k => k.Ogretmen).ToListAsync();
            return View(kurslar);
        }


        public async Task<ActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }
            var kurs = await _context
                .Kurslar
                .Include(x => x.KursKayitlari)
                .ThenInclude(x => x.Ogrenci)
                .FirstOrDefaultAsync(o => o.KursId == id);

            if (kurs == null) {
                return NotFound();
            }
            ViewBag.Ogretmenler = new SelectList(await _context.Ogretmenler.ToListAsync(), "OgretmenId", "AdSoyad");
            return View(kurs);
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> Edit(int? id, Kurs model) {
            if (id != model.KursId) {
                return NotFound();
            }
            if (ModelState.IsValid) {
                try {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) {
                    if (!_context.Kurslar.Any(o => o.KursId == model.KursId)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }



        [HttpGet]
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }
            var kurs = await _context.Kurslar.FindAsync(id);
            if (kurs == null) {
                return NotFound();
            }
            return View(kurs);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id) {
            var kurs = await _context.Kurslar.FindAsync(id);
            if (kurs == null) return NotFound();
            _context.Kurslar.Remove(kurs);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


    }
}

efcoreApp/Views/Kurs/Create.cshtml
@model Kurs;
<h2>Kurs Ekle</h2>
<hr>
<form asp-controller="Kurs" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Baslik" class="form-label">Başlık</label>
        <input asp-for="Baslik" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="OgretmenId" class="form-label">Öğretmen</label>
        <select asp-for="OgretmenId" asp-items="ViewBag.Ogretmenler" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>

    <button type="submit" class="btn btn-secondary">Kaydet</button>

</form>
    

efcoreApp/Views/Kurs/Delete.cshtml
@model Kurs

<p>
    <b>@Model.Baslik </b> isimli öğrenciyi silmek istiyor musunuz?
    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" value="@Model.KursId">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn btn-primary">Hayır</a>
    </form>
</p>

efcoreApp/Views/Kurs/Edit.cshtml
@model Kurs

<h2>Öğrenci Güncelleme</h2>
<hr>

<div class="row">
    <div class="col-8">
        <form asp-controller="Kurs" asp-action="Edit" method="post">
            <input type="hidden" asp-for="KursId">
            <div class="mb-3">
                <label asp-for="Baslik" class="form-label">Öğrenci Adı</label>
                <input asp-for="Baslik" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="OgretmenId" class="form-label">Öğretmen</label>
                <select asp-for="OgretmenId" asp-items="ViewBag.Ogretmenler" class="form-select">
                    <option value="">Seçiniz</option>
                </select>
            </div>

            <button type="submit" class="btn btn-secondary">Kaydet</button>
        </form>
    </div>
    <div class="col-4">
        <h4>Öğrenciler</h4>
        <hr>
        <ul>
            @foreach (var item in Model.KursKayitlari)
            {
                <li>@item.Ogrenci.AdSoyad</li>
            }
        </ul>

    </div>
</div>

efcoreApp/Views/Kurs/Index.cshtml
@model IEnumerable<Kurs>

<h2>Kurs Listesi</h2>
<a href="/Kurs/Create" class="btn btn-primary">Kurs Ekle</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m=> m.KursId)</th>
            <th>@Html.DisplayNameFor(m=> m.Baslik)</th>
            <th>@Html.DisplayNameFor(m=> m.Ogretmen.AdSoyad)</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.KursId)</td>
                <td>@Html.DisplayFor(m => item.Baslik)</td>
                <td>@Html.DisplayFor(m => item.Ogretmen.AdSoyad)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.KursId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.KursId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>